language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:  
  - npm install -g @angular/cli

script:
  - ng lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mtech
  on:
    branch: master
