language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:  
  - npm install
  - npm install -g @angular/cli
  - npm install -g yarn

script:
  - yarn lint
  - yarn test
  - yarn build --base-href https://olabmw.github.io/mtech/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mtech
  on:
    branch: master
